### ISSUE TITLE
Using in unit tests

### ISSUE THREAD

**Issue by nyurik** [nlopes/database-schema#7]
Is it possible to use this crate in-memory, without any I/O?  I am writing unit tests that ensure that my SQLite DB is what I expect it to be, and for that I would ideally like to have an equivalent of `.dump` command, all comparable in-memory (i.e. using the [insta project](https://insta.rs/docs/quickstart/)).  Ideally, this crate would also dump the content of all the tables.  Note that the SQLite DBs might also be in-memory, e.g. `file:myfile.sqlite?mode=memory&cache=shared` -- this would stay in memory, but will be shared among multiple connections as needed.

Usage example - comparing the entire dump of a sqlite file to the auto-managed snapshot yaml file:

```rust
insta::assert_yaml_snapshot!(sqlite_dump!("/path/to/my_file.sqlite"));
```

**Comment by nlopes** [comment]
I'm afraid as of its current state it is not. I think it would be somewhat trivial to allow `sqlite` - with MySQL and PostgreSQL (I know you haven't mentioned those but the crate supports them) it's harder without I/O just out of side effects of running mysqldump and pg_dump.

Actually it might just be a case of changing the visibility of a function:
- https://github.com/nlopes/database-schema/blob/051e6a85b4d3c8d328884540305c5122f5833da4/src/sqlite/sqlx.rs#L21

Alternatively, add a new macro that calls that function (which is what you hinted at).

Would that work for you? (This doesn't include dumping the content of the tables - this crate only looks at the schema)

**Comment by nyurik** [comment]
@nlopes thx for quick reply! I ended up writing this code as i need both the schema and the data.  It is not perfect (cuts a few corners like blob handling), but it allows me to easily dump the entire content of a sqlite database to a snapshot file as part of my integration tests:

```rust
#[derive(Debug, sqlx::FromRow, Serialize)]
struct SqliteEntry {
    pub r#type: Option<String>,
    pub tbl_name: Option<String>,
    pub sql: Option<String>,
    #[sqlx(skip)]
    pub values: Option<Vec<String>>,
}

async fn dump(conn: &mut SqliteConnection) -> Result<Vec<SqliteEntry>, sqlx::Error> {
    let mut result = Vec::new();

    let schema: Vec<SqliteEntry> = query_as(
        "SELECT type, tbl_name, sql
         FROM sqlite_schema
         ORDER BY CASE WHEN type = 'table' THEN 1 ELSE 2 END, type, tbl_name",
    )
    .fetch_all(&mut *conn)
    .await?;

    for mut entry in schema {
        let tbl = match (&entry.r#type, &entry.tbl_name) {
            (Some(typ), Some(tbl)) if typ == "table" => tbl,
            _ => {
                result.push(entry);
                continue;
            }
        };

        let sql = format!("PRAGMA table_info({tbl})");
        let columns: Vec<_> = query(&sql)
            .fetch_all(&mut *conn)
            .await?
            .into_iter()
            .map(|row| {
                let cid: i32 = row.get(0);
                let typ: String = row.get(2);
                (cid as usize, typ)
            })
            .collect();

        let sql = format!("SELECT * FROM {tbl}");
        let rows = query(&sql).fetch_all(&mut *conn).await?;
        let values = rows
            .iter()
            .map(|row| {
                let val = columns
                    .iter()
                    .map(|(idx, typ)| {
                        (match typ.as_str() {
                            "INTEGER" => row.get::<Option<i32>, _>(idx).map(|v| v.to_string()),
                            "REAL" => row.get::<Option<f64>, _>(idx).map(|v| v.to_string()),
                            "TEXT" => row
                                .get::<Option<String>, _>(idx)
                                .map(|v| format!("'{v}'")),
                            "BLOB" => row
                                .get::<Option<Vec<u8>>, _>(idx)
                                .map(|v| format!("'{}'", from_utf8(&v).unwrap())),
                            _ => panic!("Unknown column type: {typ}"),
                        })
                        .unwrap_or("NULL".to_string())
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("(  {val}  )")
            })
            .collect::<Vec<_>>();

        entry.values = Some(values);
        result.push(entry);
    }

    Ok(result)
}
```

**Comment by nlopes** [comment]
Ah nice, yeah that does the trick. Would you find it valuable to include an auxiliary function to do just that as part of this crate?

**Comment by nyurik** [comment]
I don't think it would -- its just a few lines, and I would have to sort the result to ensure tables go first -- probably not worth it.

That said, I would love to drop my implementation if favor of anything that implements sqlite3's `.dump` command without any temporary files, and without requiring to have `sqlite3` binary available.  Basically a simple `fn dump(connection) -> String` that I can save as a snapshot and diff against on each test.
